### PR TITLE
Content search

### PR DESCRIPTION
**Pull request by bmjames**
There are still a few fields of the response left to implement, but what's implemented so far works, so if @robertberry and @janua are happy with the way this is going, I'd like to merge it to master.

gif

### CODE REVIEW

**Comment by robertberry-zz** [comment]
Lovely stuff. I especially like the Morrissey example. :+1

**Comment by janua** [comment]
This looks good. Aeson is nice, and Thyme is new to me!

**Comment by bmjames** [comment]
Thyme has a few nice things (lenses and human-readable formatting functions). But for compatibility, I think it might be more sensible to just use `Data.Time` from the base libraries here.

**Comment by janua** [comment]
@bmjames Isn't Thyme a drop in replacement though?

**Comment by bmjames** [comment]
@janua it may be for us, but client code will also have to use Thyme to handle our date values. Thyme's data types are its own, not re-exports of Data.Time types.

**Pull request merged**
